{
 "title": "Main Dashboard",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "Nodes",
    "label": "Nodes",
    "query": "SELECT \n  concat(long_name, ' (', node_id, ')') as __text, \n  node_id as __value \nFROM node_details \nORDER BY long_name"
   }
  ]
 },
 "panels": [
  {
   "title": "Total nodes in mesh",
   "type": "stat",
   "description": "Total number of observed nodes in the mesh",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "nodes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(node_id) FROM node_details WHERE node_id <> '0' LIMIT 50 "
    }
   ]
  },
  {
   "title": "Active nodes in the last 30 minutes",
   "type": "stat",
   "description": "Nodes that sent any packet in the last 30 minutes",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "nodes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) \nFROM node_details \nWHERE updated_at  >= NOW() - INTERVAL '30 minutes';"
    }
   ]
  },
  {
   "title": "Nodes naming status",
   "type": "stat",
   "description": "How many nodes are unknown and how many are known.\n\nThe unknown are ones that are either NULL in their long name or \"Unknown\" in their value",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "nodes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    COUNT(CASE WHEN long_name IS NULL OR long_name = 'Unknown' AND node_id != '0' THEN 1 END) AS \"Unnamed\",\n    COUNT(CASE WHEN long_name IS NOT NULL AND long_name != 'Unknown' AND node_id != '0' THEN 1 END) AS \"Named\"\nFROM\n    node_details\n\n"
    }
   ]
  },
  {
   "title": "MQTT Node status",
   "type": "stat",
   "description": "Status of nodes in the MQTT server",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(mqtt_status), mqtt_status FROM node_details WHERE (COALESCE(mqtt_status, '') <> '' AND mqtt_status NOT LIKE '%none%' AND mqtt_status NOT LIKE '%Unknown%') GROUP BY mqtt_status LIMIT 50 "
    }
   ]
  },
  {
   "title": "Total packets sent",
   "type": "stat",
   "description": "Total packets sent in specified time range",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Packets" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum by(portnum) (mesh_packet_source_types_total{source_id=~\"$Nodes\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data sent on mesh in last hour",
   "type": "stat",
   "description": "Shows the total data sent on the mesh in bytes in the last hour. This includes all types of packets.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(text_message_app_size_in_bytes{source_id=~\"$Nodes\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Highlighted Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  { "title": "Main Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Channel Utilization (ChUtil)",
   "type": "timeseries",
   "description": "Shows the max recorded chanel utilization and the average",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket('5 minutes', time) AS time,\n  AVG(channel_utilization) AS \"Avg Channel Utilization\"\nFROM device_metrics\nWHERE $__timeFilter(time)\n  AND channel_utilization IS NOT NULL\n  AND channel_utilization > 0\n  AND node_id IN ($Nodes)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Duty Cycle (AirUtilTX)",
   "type": "timeseries",
   "description": "This panel shows the percentage of airtime used for transmissions in the last hour. Airtime in LoRa networks represents the duration a device occupies the radio frequency channel to send data. It's a critical metric for:\n\nNetwork capacity: Higher airtime usage indicates increased network load.\n\nRegulatory compliance: Many regions limit the total airtime per device.\n\nBattery life: More airtime generally means higher power consumption.\n\nThe data comes from Meshtastic packets, reflecting actual network usage. High percentages may suggest the need for optimization or capacity planning.",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket('5 minutes', dm.time) AS time,\n  COALESCE(nd.long_name, dm.node_id) AS metric,\n  AVG(dm.air_util_tx) AS value\nFROM device_metrics dm\nLEFT JOIN node_details nd ON dm.node_id = nd.node_id\nWHERE $__timeFilter(dm.time)\n  AND dm.air_util_tx IS NOT NULL\n  AND dm.air_util_tx > 0\n  AND dm.node_id IN ($Nodes)\nGROUP BY 1, 2\nORDER BY 1, 2"
    }
   ]
  },
  {
   "title": "Top channel utilizers",
   "type": "timeseries",
   "description": "Displays the nodes that utilize most of the channel (On average with at least 1 update every hour)",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "WITH top_nodes AS (\n  SELECT dm.node_id\n  FROM device_metrics dm\n  WHERE $__timeFilter(dm.time)\n    AND dm.channel_utilization IS NOT NULL\n    AND dm.channel_utilization > 0\n    AND dm.node_id IN ($Nodes)\n    AND dm.node_id IN (\n      SELECT DISTINCT node_id\n      FROM device_metrics\n      WHERE time >= NOW() - INTERVAL '1 hour'\n        AND channel_utilization IS NOT NULL\n        AND channel_utilization > 0\n    )\n  GROUP BY dm.node_id\n  ORDER BY AVG(dm.channel_utilization) DESC\n  LIMIT 3\n)\nSELECT\n  time_bucket('5 minutes', dm.time) AS time,\n  AVG(dm.channel_utilization) AS value,\n  COALESCE(nd.short_name || ':' || nd.long_name, dm.node_id) AS metric\nFROM device_metrics dm\nLEFT JOIN node_details nd ON dm.node_id = nd.node_id\nWHERE $__timeFilter(dm.time)\n  AND dm.channel_utilization IS NOT NULL\n  AND dm.channel_utilization > 0\n  AND dm.node_id IN (SELECT node_id FROM top_nodes)\nGROUP BY 1, 3\nORDER BY 1, 3"
    }
   ]
  },
  {
   "title": "Packet types for selected time",
   "type": "piechart",
   "description": "Displays types of packets in the selected time range.\n\nFor more details see:\nhttps://buf.build/meshtastic/protobufs/docs/main:meshtastic#meshtastic.PortNum",
   "gridPos": { "h": 9, "w": 4, "x": 11, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "Packets" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(portnum) (mesh_packet_source_types_total{source_id=~\"$Nodes\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "The configured max hops for each client",
   "type": "gauge",
   "description": "How many hops are configured for each client",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "hops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(\n  mesh_packet_hop_start{source_id=~\"$Nodes\"}\n  and\n  (delta(mesh_packet_hop_start{source_id=~\"$Nodes\"}[1m]) != 0)\n) by (source_id, source_long_name)",
     "legendFormat": "{{source_long_name}}"
    }
   ]
  },
  {
   "title": "Node Graph",
   "type": "nodeGraph",
   "description": "Graph that is built from Neighbor Info reports and shows the signal strenth for each line",
   "gridPos": { "h": 22, "w": 11, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT\n    cd.node_id AS \"id\",\n    cd.long_name AS \"title\",\n    cd.hardware_model AS \"detail__Hardware Detail\",\n    cd.role AS \"detail__Client Role\",\n    cd.mqtt_status AS \"detail__MQTT Status\",\n    cd.short_name AS \"subtitle\",\n    CASE\n        WHEN cd.mqtt_status = 'online' THEN '#2ECC71' -- Green for online\n        WHEN cd.mqtt_status = 'offline' THEN '#E74C3C' -- Red for offline\n        ELSE '#808080' -- Gray for none or any other status\n    END AS \"color\"\nFROM\n    node_details cd\nLEFT JOIN (\n    SELECT node_id FROM node_neighbors\n    UNION\n    SELECT neighbor_id FROM node_neighbors\n) nn ON cd.node_id = nn.node_id\nWHERE nn.node_id IS NOT NULL"
    },
    {
     "rawSql": "SELECT \n    CONCAT(neighbor_id, '_', node_id) AS id,\n    neighbor_id AS \"source\",\n    node_id AS \"target\",\n    snr AS \"mainstat\",\n    CASE\n        WHEN snr < -13 THEN '#E74C3C'  -- Red for SNR < -13\n        WHEN snr < -7 THEN '#F4D03F'   -- Yellow for -13 ≤ SNR < -7\n        ELSE '#2ECC71'                 -- Green for SNR ≥ -7\n    END AS \"color\",\n    GREATEST(0.1, LEAST(2, 1 + ((snr + 13) / 10))) AS \"thickness\"\nFROM \n    node_neighbors"
    }
   ]
  },
  {
   "title": "General Information",
   "type": "table",
   "description": "Information stored on the Redis DB which includes \"hard to get\" information - that is needed to be gathered over time.",
   "gridPos": { "h": 22, "w": 13, "x": 11, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT * FROM node_details WHERE node_id <> '0' "
    }
   ]
  },
  {
   "title": "Nodes map",
   "type": "geomap",
   "description": "Displays the nodes on the map",
   "gridPos": { "h": 25, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "rawSql": "SELECT * FROM node_details WHERE longitude != 0 AND longitude IS NOT NULL"
    }
   ]
  }
 ]
}