{
 "title": "Node Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "nodeID",
    "label": "Node ID",
    "query": "SELECT \n  concat(long_name, ' (', node_id, ')') as __text, \n  node_id as __value \nFROM node_details \nORDER BY long_name"
   },
   {
    "name": "relatives",
    "label": "relatives",
    "query": "SELECT \n    neighbor_id AS \"source\",\n    node_id AS \"target\"\nFROM \n    node_neighbors_latest\nWHERE node_id = ${nodeID:singlequote} OR neighbor_id = ${nodeID:singlequote}"
   }
  ]
 },
 "panels": [
  {
   "title": "Total packets sent",
   "type": "stat",
   "description": "Total packets sent in the specified time range",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Packets" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum by(portnum) (mesh_packet_source_types_total{source_id=~\"$nodeID\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Packet types sent for selected time",
   "type": "stat",
   "description": "Displays types of packets sent in the selected time range.\n\nFor more details see:\nhttps://buf.build/meshtastic/protobufs/docs/main:meshtastic#meshtastic.PortNum",
   "gridPos": { "h": 4, "w": 14, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Packets" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(portnum) (mesh_packet_source_types_total{source_id=~\"$nodeID\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last packet sent",
   "type": "stat",
   "description": "The last time a packet was observed being sent from this node",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "timestamp((\n  count(mesh_packet_total{source_id=\"$nodeID\"}) by (source_id)\n  -\n  count(mesh_packet_total{source_id=\"$nodeID\"} offset 1m) by (source_id)\n) > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total packets received",
   "type": "stat",
   "description": "Total packets observed with this node as their destination in the specified time range",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Packets" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum by(portnum) (mesh_packet_source_types_total{destination_id=~\"$nodeID\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Packet types received for selected time",
   "type": "stat",
   "description": "Displays types of packets received in the selected time range.\n\nFor more details see:\nhttps://buf.build/meshtastic/protobufs/docs/main:meshtastic#meshtastic.PortNum",
   "gridPos": { "h": 4, "w": 14, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Packets" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(portnum) (mesh_packet_source_types_total{destination_id=\"$nodeID\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last message received",
   "type": "stat",
   "description": "The last time a packet was observed with this node as its destination",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "timestamp((\n  count(mesh_packet_total{destination_id=\"$nodeID\"}) by (destination_id)\n  -\n  count(mesh_packet_total{destination_id=\"$nodeID\"} offset 1m) by (destination_id)\n) > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node details",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT * FROM node_details WHERE node_id = '${nodeID}' LIMIT 1 "
    }
   ]
  },
  {
   "title": "Node Graph",
   "type": "nodeGraph",
   "description": "Graph that is built from Neighbor Info reports and shows the signal strenth for each line",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT \n    node_id AS \"id\", \n    long_name AS \"title\", \n    hardware_model AS \"detail__Hardware Detail\", \n    role AS \"detail__Client Role\", \n    mqtt_status AS \"detail__MQTT Status\", \n    short_name AS \"subtitle\",\n    CASE \n        WHEN mqtt_status = 'online' THEN '#2ECC71'  -- Green for online\n        WHEN mqtt_status = 'offline' THEN '#E74C3C' -- Red for offline\n        ELSE '#808080'                              -- Gray for none or any other status\n    END AS \"color\"\nFROM \n    node_details\n    WHERE node_id IN (${nodeID:singlequote}) OR node_id IN (${relatives:singlequote})"
    },
    {
     "rawSql": "SELECT \n    CONCAT(neighbor_id, '_', node_id) AS id,\n    neighbor_id AS \"source\",\n    node_id AS \"target\",\n    snr AS \"mainstat\",\n    CASE\n        WHEN snr < -13 THEN '#E74C3C'  -- Red for SNR < -13\n        WHEN snr < -7 THEN '#F4D03F'   -- Yellow for -13 ≤ SNR < -7\n        ELSE '#2ECC71'                 -- Green for SNR ≥ -7\n    END AS \"color\",\n    GREATEST(0.1, LEAST(2, 1 + ((snr + 13) / 10))) AS \"thickness\"\nFROM \n    node_neighbors_latest\n    WHERE (neighbor_id IN (${nodeID:singlequote}) OR neighbor_id IN (${relatives:singlequote}))\n    AND (node_id IN (${nodeID:singlequote}) OR node_id IN (${relatives:singlequote}))"
    }
   ]
  },
  {
   "title": "Temprerature telemetry",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 9, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "topk(1, telemetry_app_temperature{node_id=\"$nodeID\"})",
     "legendFormat": "{{long_name}}"
    }
   ]
  },
  {
   "title": "Node configuration details",
   "type": "table",
   "gridPos": { "h": 15, "w": 7, "x": 17, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT\n  node_id,\n  CASE\n    WHEN EXTRACT(EPOCH FROM environment_update_interval) > 1\n    THEN to_char(environment_update_interval, 'HH24:MI:SS')\n    ELSE NULL\n  END AS environment_update_interval,\n  to_char(environment_update_last_timestamp, 'YYYY-MM-DD HH24:MI:SS') AS environment_update_last_timestamp,\n  \n  CASE\n    WHEN EXTRACT(EPOCH FROM device_update_interval) > 1\n    THEN to_char(device_update_interval, 'HH24:MI:SS')\n    ELSE NULL\n  END AS device_update_interval,\n  to_char(device_update_last_timestamp, 'YYYY-MM-DD HH24:MI:SS') AS device_update_last_timestamp,\n  \n  CASE\n    WHEN EXTRACT(EPOCH FROM air_quality_update_interval) > 1\n    THEN to_char(air_quality_update_interval, 'HH24:MI:SS')\n    ELSE NULL\n  END AS air_quality_update_interval,\n  to_char(air_quality_update_last_timestamp, 'YYYY-MM-DD HH24:MI:SS') AS air_quality_update_last_timestamp,\n  \n  CASE\n    WHEN EXTRACT(EPOCH FROM power_update_interval) > 1\n    THEN to_char(power_update_interval, 'HH24:MI:SS')\n    ELSE NULL\n  END AS power_update_interval,\n  to_char(power_update_last_timestamp, 'YYYY-MM-DD HH24:MI:SS') AS power_update_last_timestamp,\n  \n  CASE\n    WHEN EXTRACT(EPOCH FROM range_test_interval) > 1\n    THEN to_char(range_test_interval, 'HH24:MI:SS')\n    ELSE NULL\n  END AS range_test_interval,\n  to_char(range_test_last_packet_timestamp, 'YYYY-MM-DD HH24:MI:SS') AS range_test_last_packet_timestamp,\n  \n  CASE\n    WHEN EXTRACT(EPOCH FROM pax_counter_interval) > 1\n    THEN to_char(pax_counter_interval, 'HH24:MI:SS')\n    ELSE NULL\n  END AS pax_counter_interval,\n  to_char(pax_counter_last_timestamp, 'YYYY-MM-DD HH24:MI:SS') AS pax_counter_last_timestamp,\n  \n  CASE\n    WHEN EXTRACT(EPOCH FROM neighbor_info_interval) > 1\n    THEN to_char(neighbor_info_interval, 'HH24:MI:SS')\n    ELSE NULL\n  END AS neighbor_info_interval,\n  to_char(neighbor_info_last_timestamp, 'YYYY-MM-DD HH24:MI:SS') AS neighbor_info_last_timestamp,\n  \n  CASE\n    WHEN EXTRACT(EPOCH FROM map_broadcast_interval) > 1\n    THEN to_char(map_broadcast_interval, 'HH24:MI:SS')\n    ELSE NULL\n  END AS map_broadcast_interval,\n  to_char(map_broadcast_last_timestamp, 'YYYY-MM-DD HH24:MI:SS') AS map_broadcast_last_timestamp,\n  \n  mqtt_encryption_enabled,\n  mqtt_json_enabled,\n  mqtt_configured_root_topic,\n  to_char(mqtt_info_last_timestamp, 'YYYY-MM-DD HH24:MI:SS') AS mqtt_info_last_timestamp,\n  \n  to_char(last_updated, 'YYYY-MM-DD HH24:MI:SS') AS last_updated\nFROM node_configurations\nWHERE\n  (EXTRACT(EPOCH FROM environment_update_interval) > 1 OR\n   EXTRACT(EPOCH FROM device_update_interval) > 1 OR\n   EXTRACT(EPOCH FROM air_quality_update_interval) > 1 OR\n   EXTRACT(EPOCH FROM power_update_interval) > 1 OR\n   EXTRACT(EPOCH FROM range_test_interval) > 1 OR\n   EXTRACT(EPOCH FROM pax_counter_interval) > 1 OR\n   EXTRACT(EPOCH FROM neighbor_info_interval) > 1 OR\n   EXTRACT(EPOCH FROM map_broadcast_interval) > 1)\n  AND node_id = '${nodeID}'\nLIMIT 50"
    }
   ]
  },
  {
   "title": "Humidity telemetry",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 9, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "expr": "topk(1, telemetry_app_relative_humidity{node_id=\"$nodeID\"})",
     "legendFormat": "{{long_name}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "geomap",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT node_id, short_name, long_name, hardware_model, role, mqtt_status, \nlongitude * 1e-7 as longitude,\nlatitude * 1e-7 as latitude,\naltitude\nFROM node_details \nWHERE node_id = '${nodeID}' LIMIT 1"
    }
   ]
  },
  {
   "title": "Barometric pressure telemetry",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 9, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "expr": "topk(1, telemetry_app_barometric_pressure{node_id=\"$nodeID\"})",
     "legendFormat": "{{long_name}}"
    }
   ]
  },
  {
   "title": "Battery Level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "telemetry_app_battery_level{node_id=\"$nodeID\"}",
     "legendFormat": "{{long_name}} | Model: {{hardware_model}} | Role: {{role}}"
    }
   ]
  },
  {
   "title": "Device voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "telemetry_app_voltage{node_id=\"$nodeID\"}",
     "legendFormat": "{{long_name}} | Model: {{hardware_model}} | Role: {{role}}"
    }
   ]
  },
  {
   "title": "Current measured from node",
   "type": "timeseries",
   "description": "Displays the measured current from the channels (1,2,3)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    {
     "expr": "telemetry_app_ch1_current{node_id=\"$nodeID\"}",
     "legendFormat": "Channel 1"
    },
    {
     "expr": "telemetry_app_ch2_current{node_id=\"$nodeID\"}",
     "legendFormat": "Channel 2"
    },
    {
     "expr": "telemetry_app_ch3_current{node_id=\"$nodeID\"}",
     "legendFormat": "Channel 3"
    }
   ]
  },
  {
   "title": "Voltage measured by the node",
   "type": "timeseries",
   "description": "Measures the volage on channels (1,2,3)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "telemetry_app_ch1_voltage{node_id=\"$nodeID\"}",
     "legendFormat": "Channel 1"
    },
    {
     "expr": "telemetry_app_ch2_voltage{node_id=\"$nodeID\"}",
     "legendFormat": "Channel 2"
    },
    {
     "expr": "telemetry_app_ch3_voltage{node_id=\"$nodeID\"}",
     "legendFormat": "Channel 3"
    }
   ]
  }
 ]
}